metadata:
  favicon: ''
  title: 'Sociální sítě '
  description: ''
  breakpoints: []
  rendererCachingEnabled: true
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
internalType: project
